//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Security.Policy;
    using System.Web.Services.Description;

    public partial class Admin
    {
        public int UserId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name is required")]
        [Display(Name = " First Name: ")]
        public string FirstName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name is required")]
        [Display(Name = " Last Name: ")]
        public string LastName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email is required")]
        [Display(Name = " Email ID: ")]
        public string EmailId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password  is required")]
        [Display(Name = " Password: ")]
        [DataType(DataType.Password)]

        public string Password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = " Confrim Password  is required")]
        [Display(Name = " Confirm Password: ")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = " Confrim Password and Password Should be same")]
        public string ConfirmPassword { get; set; }
        public string SuccessMessage { get; set; }
    }
}

