//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingManagementSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Park
    {
        public int CoustID { get; set; }
        public string CoustName { get; set; }
        public string VechicalNO { get; set; }
        public string MobileNO { get; set; }
        public string ParkingArea { get; set; }
        public int SlotNo { get; set; }
        public string EnterTime { get; set; }
        public string ExitTime { get; set; }
    }
}
